# Generated by Django 2.2.3 on 2019-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191216_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.TextField(default='This will be displayed as header of your page, edit it in admin panel!'),
        ),
    ]
