# Generated by Django 2.2.3 on 2019-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_homepage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='This will be displayed as header of your page, edit it in admin panel!', max_length=512),
        ),
    ]
