# Generated by Django 2.2.3 on 2019-12-16 17:01

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191216_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='Other_Enchancements',
            field=djrichtextfield.models.RichTextField(default='', max_length=500),
        ),
    ]
