# Generated by Django 2.2.3 on 2019-12-16 19:02

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191216_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='Breed_name',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Evolves_from',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Evolves_to',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Other_Enchancements',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
    ]
