# Generated by Django 2.2.3 on 2019-12-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191216_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='icon',
            field=models.ImageField(default='defaults/creature_icon.png', upload_to='creature_icons/'),
        ),
    ]
