# Generated by Django 2.2.3 on 2019-12-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_creature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='creature_icons/'),
        ),
    ]
