# Generated by Django 2.2.3 on 2019-12-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_creature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='Evolves_from',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Evolves_to',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Fluff',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Other_Enchancements',
            field=models.TextField(default=''),
        ),
    ]
