# Generated by Django 2.2.3 on 2019-12-22 16:13

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191222_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='Evolves_from',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Evolves_to',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Fluff',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Other_Enchancements',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
    ]
