# Generated by Django 2.2.3 on 2019-12-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191222_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='icon',
        ),
        migrations.AlterField(
            model_name='creature',
            name='Evolves_from',
            field=models.TextField(default='<p></p>'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Evolves_to',
            field=models.TextField(default='<p></p>'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Fluff',
            field=models.TextField(default='<p></p>'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='Other_Enchancements',
            field=models.TextField(default='<p></p>'),
        ),
    ]
