# Generated by Django 2.2.3 on 2019-12-23 13:49

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20191222_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='Other_Enchancements',
            field=djrichtextfield.models.RichTextField(default='<p></p>'),
        ),
    ]
