# Generated by Django 2.2.3 on 2019-12-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191223_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='Other_Enchancements',
            field=models.TextField(default='<p></p>'),
        ),
    ]
