# Generated by Django 2.2.3 on 2019-12-23 15:03

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191223_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='Other_Enchancements',
            field=djrichtextfield.models.RichTextField(default='<p></p>'),
        ),
    ]
